load("config.js");

function execute() {
    let url = BASE_URL
    let response = fetch(url)
    if (response.ok) {
        var data = [
            { title: "Truyện loạn luân", input: BASE_URL + "/tag/truyen-sex-loan-luan", script: "gen3.js" },
            { title: "Truyện không loạn luân", input: BASE_URL + "/tag/truyen-khong-loan-luan", script: "gen3.js" },
            { title: "Truyện sex có thật", input: BASE_URL + "/tag/truyen-sex-co-that", script: "gen3.js" },
            { title: "Truyện sex ngoại tình", input: BASE_URL + "/tag/truyen-sex-ngoai-tinh", script: "gen3.js" },
            { title: "Truyện sex hiếp dâm", input: BASE_URL + "/tag/truyen-sex-hiep-dam", script: "gen3.js" },
            { title: "Truyện sex phá trinh", input: BASE_URL + "/tag/truyen-sex-pha-trinh", script: "gen3.js" },
            { title: "Truyện sex bạo dâm", input: BASE_URL + "/tag/truyen-sex-bao-dam", script: "gen3.js" },
            { title: "Truyện sex khổ dâm", input: BASE_URL + "/tag/truyen-sex-kho-dam", script: "gen3.js" },
            { title: "Truyện sex cưỡng dâm", input: BASE_URL + "/tag/truyen-sex-cuong-dam", script: "gen3.js" },
            { title: "Truyện NTR", input: BASE_URL + "/tag/truyen-ntr", script: "gen3.js" },
            { title: "Truyện Cuckold", input: BASE_URL + "/tag/truyen-sex-cuckold", script: "gen3.js" },
            { title: "Tâm sự bạn đọc", input: BASE_URL + "/tag/tam-su-ban-doc", script: "gen3.js" },
            { title: "Cho người khác đụ vợ mình", input: BASE_URL + "/tag/cho-nguoi-khac-du-vo-minh", script: "gen3.js" },
            { title: "Con gái thủ dâm", input: BASE_URL + "/tag/con-gai-thu-dam", script: "gen3.js" },
            { title: "Đụ công khai", input: BASE_URL + "/tag/du-cong-khai", script: "gen3.js" },
            { title: "Trao đổi vợ chồng", input: BASE_URL + "/tag/trao-doi-vo-chong", script: "gen3.js" },
            { title: "Truyện les", input: BASE_URL + "/tag/truyen-les", script: "gen3.js" },
            { title: "Thác loạn tập thể", input: BASE_URL + "/tag/thac-loan-tap-the", script: "gen3.js" },
            { title: "Đụ tập thể", input: BASE_URL + "/tag/du-tap-the", script: "gen3.js" },
            { title: "Làm tình tay ba", input: BASE_URL + "/tag/lam-tinh-tay-ba", script: "gen3.js" },
            { title: "Dùng sextoys", input: BASE_URL + "/tag/sextoy", script: "gen3.js" },
            { title: "Truyện sex tống tình", input: BASE_URL + "/tag/truyen-sex-tong-tinh", script: "gen3.js" },
            { title: "Thuốc kích dục", input: BASE_URL + "/tag/thuoc-kich-duc", script: "gen3.js" },
            { title: "Truyện sex mạnh", input: BASE_URL + "/tag/truyen-sex-manh", script: "gen3.js" },
            { title: "Truyện sex nhẹ nhàng", input: BASE_URL + "/tag/truyen-sex-nhe-nhang", script: "gen3.js" },
            { title: "Truyện bóp vú", input: BASE_URL + "/tag/truyen-bop-vu", script: "gen3.js" },
            { title: "Truyện bú cặc", input: BASE_URL + "/tag/truyen-bu-cac", script: "gen3.js" },
            { title: "Truyện bú lồn", input: BASE_URL + "/tag/truyen-bu-lon", script: "gen3.js" },
            { title: "Truyện liếm đít", input: BASE_URL + "/tag/truyen-liem-dit", script: "gen3.js" },
            { title: "Đụ lỗ đít", input: BASE_URL + "/tag/du-lo-dit", script: "gen3.js" },
            { title: "Đụ thư ký", input: BASE_URL + "/tag/du-thu-ky", script: "gen3.js" },
            { title: "Truyện sex học sinh", input: BASE_URL + "/tag/truyen-sex-hoc-sinh", script: "gen3.js" },
            { title: "Truyện sex sinh viên", input: BASE_URL + "/tag/truyen-sex-sinh-vien", script: "gen3.js" },
            { title: "Truyện sex cô giáo", input: BASE_URL + "/tag/truyen-sex-co-giao", script: "gen3.js" },
            { title: "Bố chồng nàng dâu", input: BASE_URL + "/tag/bo-chong-nang-dau", script: "gen3.js" },
            { title: "Bố đụ con gái", input: BASE_URL + "/tag/bo-du-con-gai", script: "gen3.js" },
            { title: "Đụ mẹ ruột", input: BASE_URL + "/tag/du-me-ruot", script: "gen3.js" },
            { title: "Đụ mẹ vợ", input: BASE_URL + "/tag/du-me-vo", script: "gen3.js" },
            { title: "Đụ mẹ bạn", input: BASE_URL + "/tag/du-me-ban", script: "gen3.js" },
            { title: "Vợ chồng", input: BASE_URL + "/tag/vo-chong", script: "gen3.js" },
            { title: "Đụ vợ bạn", input: BASE_URL + "/tag/du-vo-ban", script: "gen3.js" },
            { title: "Đụ chị gái", input: BASE_URL + "/tag/du-chi-gai", script: "gen3.js" },
            { title: "Chị dâu em chồng", input: BASE_URL + "/tag/chi-dau-em-chong", script: "gen3.js" },
            { title: "Làm tình với chị vợ", input: BASE_URL + "/tag/lam-tinh-voi-chi-vo", script: "gen3.js" },
            { title: "Đụ em gái", input: BASE_URL + "/tag/du-em-gai", script: "gen3.js" },
            { title: "Đụ em vợ", input: BASE_URL + "/tag/du-em-vo", script: "gen3.js" },
            { title: "Đụ cháu gái", input: BASE_URL + "/tag/du-chau-gai", script: "gen3.js" },
            { title: "Đụ bạn của người yêu", input: BASE_URL + "/tag/du-ban-cua-nguoi-yeu", script: "gen3.js" },
            { title: "Làm tình với đồng nghiệp", input: BASE_URL + "/tag/lam-tinh-voi-dong-nghiep", script: "gen3.js" },
            { title: "Đụ giúp việc", input: BASE_URL + "/tag/du-gigen-viec", script: "gen3.js" },
            { title: "Đụ với hàng xóm", input: BASE_URL + "/tag/du-voi-hang-xom", script: "gen3.js" },
            { title: "Đụ cave", input: BASE_URL + "/tag/du-cave", script: "gen3.js" },
            { title: "Bác sĩ y tá", input: BASE_URL + "/tag/bac-si-y-ta", script: "gen3.js" },
            { title: "Đụ máy bay", input: BASE_URL + "/tag/du-may-bay", script: "gen3.js" },
            { title: "Người và thú", input: BASE_URL + "/tag/nguoi-va-thu", script: "gen3.js" },
            { title: "Đụ trên tàu", input: BASE_URL + "/tag/du-tren-tau", script: "gen3.js" },
            { title: "Làm tình nơi công cộng", input: BASE_URL + "/tag/lam-tinh-noi-cong-cong", script: "gen3.js" },
            { title: "Truyện teen", input: BASE_URL + "/tag/truyen-teen", script: "gen3.js" },
            { title: "Truyện cổ trang", input: BASE_URL + "/tag/truyen-co-trang", script: "gen3.js" },
            { title: "Truyện sex hay", input: BASE_URL + "/tag/truyen-sex-hay", script: "gen3.js" },
            { title: "Dâm thư trung quốc", input: BASE_URL + "/tag/dam-thu-trung-quoc", script: "gen3.js" },
            { title: "Truyện sắc hiệp", input: BASE_URL + "/tag/truyen-sac-hiep", script: "gen3.js" },
            { title: "Kinh nghiệm làm tình", input: BASE_URL + "/tag/kinh-nghiem-lam-tinh", script: "gen3.js" },
            { title: "Truyện ma quỷ", input: BASE_URL + "/tag/truyen-sex-ma-quy", script: "gen3.js" },
            { title: "Truyện Tết", input: BASE_URL + "/tag/truyen-tet", script: "gen3.js" },
            { title: "Truyện nonSEX (Không có cảnh sex)", input: BASE_URL + "/truyen-nonsex", script: "gen3.js" },
            { title: "Truyện cũ", input: BASE_URL + "/truyen-cu", script: "gen3.js" },
            { title: "Tác giả Cô Kim", input: BASE_URL + "/tag/tac-gia-co-kim", script: "gen3.js" },
            { title: "Tác giả Number Seven", input: BASE_URL + "/tag/tac-gia-number-seven", script: "gen3.js" },
            { title: "Tác giả Vi Thăng Long", input: BASE_URL + "/tag/tac-gia-vi-thang-long", script: "gen3.js" },
            { title: "Tác giả Why Not Me", input: BASE_URL + "/tag/tac-gia-why-not-me", script: "gen3.js" },
            { title: "Tác giả Leysek", input: BASE_URL + "/tag/tac-gia-leysek", script: "gen3.js" },
            { title: "Tác giả 69deluxe", input: BASE_URL + "/tag/tac-gia-69deluxe", script: "gen3.js" },
            { title: "Tác giả Giữ Lửa", input: BASE_URL + "/tag/tac-gia-giu-lua", script: "gen3.js" },
            { title: "Tác giả Hồng Nhung", input: BASE_URL + "/tag/tac-gia-hong-nhung", script: "gen3.js" },
            { title: "Tác giả Nguyễn Chuối Tiêu", input: BASE_URL + "/tag/tac-gia-nguyen-chuoi-tieu", script: "gen3.js" },
            { title: "Tác giả The Sand", input: BASE_URL + "/tag/tac-gia-the-sand", script: "gen3.js" },
            { title: "Tác giả kiehry", input: BASE_URL + "/tag/tac-gia-kiehry", script: "gen3.js" },
            { title: "Tác giả Akay Hau", input: BASE_URL + "/tag/tac-gia-akay-hau", script: "gen3.js" },
            { title: "Tác giả Ngọc Linh", input: BASE_URL + "/tag/tac-gia-ngoc-linh", script: "gen3.js" },
            { title: "Tác giả Slaydark", input: BASE_URL + "/tag/tac-gia-slaydark", script: "gen3.js" },
            { title: "Tác giả Loạn Nhân Luân", input: BASE_URL + "/tag/tac-gia-loan-nhan-luan", script: "gen3.js" },
            { title: "Tác giả Cu Zũng", input: BASE_URL + "/tag/tac-gia-cu-zung", script: "gen3.js" },
            { title: "Tác giả Lưu Manh", input: BASE_URL + "/tag/tac-gia-luu-manh", script: "gen3.js" },
            { title: "Tác giả Oceano", input: BASE_URL + "/tag/tac-gia-oceano", script: "gen3.js" },
            { title: "Tác giả Vu Sơn", input: BASE_URL + "/tag/tac-gia-vu-son", script: "gen3.js" },
            { title: "Tác giả Phượng Phò", input: BASE_URL + "/tag/tac-gia-phuong-pho", script: "gen3.js" },
            { title: "Tác giả HvH", input: BASE_URL + "/tag/tac-gia-hvh", script: "gen3.js" },
            { title: "Tác giả thichmbhanoi", input: BASE_URL + "/tag/tac-gia-thichmbhanoi", script: "gen3.js" },
            { title: "Tác giả Tại Hạ", input: BASE_URL + "/tag/tac-gia-tai-ha", script: "gen3.js" },
            { title: "Tác giả Yêu chân thành", input: BASE_URL + "/tag/tac-gia-yeu-chan-thanh", script: "gen3.js" },
            { title: "Tác giả BoyTimGirls", input: BASE_URL + "/tag/tac-gia-boytimgirls", script: "gen3.js" },
            { title: "Tác giả Hoài Cổ", input: BASE_URL + "/tag/tac-gia-hoai-co", script: "gen3.js" },
            { title: "Tác giả Traidamdulich", input: BASE_URL + "/tag/tac-gia-traidamdulich", script: "gen3.js" },
            { title: "Tác giả Tiểu Long", input: BASE_URL + "/tag/tac-gia-tieu-long", script: "gen3.js" },
            { title: "Tác giả Les Misérables", input: BASE_URL + "/tag/tac-gia-les-miserables", script: "gen3.js" },
            { title: "Tác giả MrGi", input: BASE_URL + "/tag/tac-gia-mrgi", script: "gen3.js" },
            { title: "Tác giả FrogMan", input: BASE_URL + "/tag/tac-gia-frogman", script: "gen3.js" },
            { title: "Tác giả Khởi nguồn dục vọng", input: BASE_URL + "/tag/tac-gia-khoi-nguon-duc-vong", script: "gen3.js" },
        ]
        var doc = response.html()
        doc.select(".bai-viet-box").last().remove()
        doc.select(".bai-viet-box > .list2 > strong > a").forEach(e => {
            data.push({
                title: e.text(),
                input: e.attr("href"),
                script: "gen3.js"
            })
        })
    }
    return Response.success(data)
}