function execute() {
    return Response.success([
        { title: "Tiên Hiệp", input: "/the-loai/tien-hiep", script: "gen.js" },
        { title: "Kiếm Hiệp", input: "/the-loai/kiem-hiep", script: "gen.js" },
        { title: "Ngôn Tình", input: "/the-loai/ngon-tinh", script: "gen.js" },
        { title: "Đam Mỹ", input: "/the-loai/dam-my", script: "gen.js" },
        { title: "Bách Hợp", input: "/the-loai/bach-hop", script: "gen.js" },
        { title: "Quan Trường", input: "/the-loai/quan-truong", script: "gen.js" },
        { title: "Võng Du", input: "/the-loai/vong-du", script: "gen.js" },
        { title: "Khoa Huyễn", input: "/the-loai/khoa-huyen", script: "gen.js" },
        { title: "Hệ Thống", input: "/the-loai/he-thong", script: "gen.js" },
        { title: "Huyền Huyễn", input: "/the-loai/huyen-huyen", script: "gen.js" },
        { title: "Dị Giới", input: "/the-loai/di-gioi", script: "gen.js" },
        { title: "Dị Năng", input: "/the-loai/di-nang", script: "gen.js" },
        { title: "Quân Sự", input: "/the-loai/quan-su", script: "gen.js" },
        { title: "Lịch Sử", input: "/the-loai/lich-su", script: "gen.js" },
        { title: "Xuyên Không", input: "/the-loai/xuyen-khong", script: "gen.js" },
        { title: "Xuyên Nhanh", input: "/the-loai/xuyen-nhanh", script: "gen.js" },
        { title: "Trọng Sinh", input: "/the-loai/trong-sinh", script: "gen.js" },
        { title: "Trinh Thám", input: "/the-loai/trinh-tham", script: "gen.js" },
        { title: "Linh Dị", input: "/the-loai/linh-di", script: "gen.js" },
        { title: "Ngược", input: "/the-loai/nguoc", script: "gen.js" },
        { title: "Sắc", input: "/the-loai/sac", script: "gen.js" },
        { title: "Sủng", input: "/the-loai/sung", script: "gen.js" },
        { title: "Cung Đấu", input: "/the-loai/cung-dau", script: "gen.js" },
        { title: "Nữ Cường", input: "/the-loai/nu-cuong", script: "gen.js" },
        { title: "Gia Đấu", input: "/the-loai/gia-dau", script: "gen.js" },
        { title: "Đông Phương", input: "/the-loai/dong-phuong", script: "gen.js" },
        { title: "Đô Thị", input: "/the-loai/do-thi", script: "gen.js" },
        { title: "Điền Văn", input: "/the-loai/dien-van", script: "gen.js" },
        { title: "Mạt Thế", input: "/the-loai/mat-the", script: "gen.js" },
        { title: "Truyện Teen", input: "/the-loai/truyen-teen", script: "gen.js" },
        { title: "Nữ Phụ", input: "/the-loai/nu-phu", script: "gen.js" },
        { title: "Light Novel", input: "/the-loai/light-novel", script: "gen.js" },
        { title: "Đoản Văn", input: "/the-loai/doan-van", script: "gen.js" },
        { title: "Hiện đại", input: "/the-loai/hien-dai", script: "gen.js" },
        { title: "Khác", input: "/the-loai/khac", script: "gen.js" },
        { title: "Truyện Full", input: "/danh-sach/truyen-full", script: "gen.js" },
        { title: "Truyện Hot", input: "/danh-sach/truyen-hot", script: "gen.js" },
        { title: "Ngôn Tình Ngắn", input: "/danh-sach/truyen-ngon-tinh-ngan", script: "gen.js" },
        { title: "Ngôn Tình Hay", input: "/danh-sach/truyen-ngon-tinh-hay", script: "gen.js" },
        { title: "Ngôn Tình 18+", input: "/danh-sach/truyen-ngon-tinh-18", script: "gen.js" },
        { title: "Ngôn Tình Hoàn", input: "/danh-sach/truyen-ngon-tinh-hoan", script: "gen.js" },
        { title: "Ngôn Tình Ngược", input: "/danh-sach/truyen-ngon-tinh-nguoc", script: "gen.js" },
        { title: "Ngôn Tình Sủng", input: "/danh-sach/truyen-ngon-tinh-sung", script: "gen.js" },
        { title: "Ngôn Tình Hài", input: "/danh-sach/truyen-ngon-tinh-hai-huoc", script: "gen.js" },
        { title: "Ngôn Tình Sắc", input: "/danh-sach/truyen-ngon-tinh-sac", script: "gen.js" },
        { title: "Truyện Teen Hay", input: "/danh-sach/truyen-teen-hay", script: "gen.js" },
        { title: "Kiếm Hiệp Hay", input: "/danh-sach/truyen-kiem-hiep-hay", script: "gen.js" },
        { title: "Tiên Hiệp Hay", input: "/danh-sach/truyen-tien-hiep-hay", script: "gen.js" }
    ]);
}